apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: backend-pipeline
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: git-url
      type: string
    - name: git-revision
      type: string
      default: main
    - name: image-name
      type: string
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: test-backend
      runAfter: ["fetch-repository"]
      taskRef:
        name: test-backend
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: build-push-backend-image
      runAfter: ["test-backend"]
      taskRef:
        name: build-push-backend-image
      params:
        - name: IMAGE
          value: $(params.image-name)
      workspaces:
        - name: source
          workspace: shared-workspace