apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: docker.io/abdullahom/counter-app-fe:latest
        imagePullPolicy: Always  # Add this line
        ports:
        - containerPort: 8080
