apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-push-backend-image
spec:
  params:
    - name: IMAGE
      description: Name (reference) of the image to build
    - name: DOCKERFILE
      description: Path to the Dockerfile to build
      default: ./Dockerfile
  workspaces:
    - name: source
  steps:
    - name: build-and-push
      image: quay.io/buildah/stable:v1.23.1
      env:
        - name: REGISTRY_AUTH_FILE
          value: /tekton/home/.docker/config.json
      workingDir: $(workspaces.source.path)/counter-app-backend
      # securityContext:
      #   privileged: true
      script: |
        buildah --storage-driver=vfs bud --format=docker --tls-verify=false --no-cache -f $(params.DOCKERFILE) -t $(params.IMAGE) .
        buildah --storage-driver=vfs push --tls-verify=false $(params.IMAGE)