apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-frontend
spec:
  workspaces:
    - name: source
  steps:
    - name: build
      image: node:14
      workingDir: $(workspaces.source.path)/frontend
      script: |
        npm install
        npm run build
        echo "Frontend build completed"