apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  params:
    - name: url
      type: string
      description: git url to clone
    - name: revision
      type: string
      description: git revision to checkout (branch, tag, sha, ref…)
      default: ""
  workspaces:
    - name: source
      description: The git repo will be cloned onto the volume backing this workspace
  steps:
    - name: git-clone
      image: alpine/git:v2.26.2
      script: |
        export HOME="/tekton/home"
        git config --global --add safe.directory '$(workspaces.source.path)'
        git clone $(params.url) $(workspaces.source.path)
        cd $(workspaces.source.path)
        echo "current working dir"
        pwd
        echo "file list"
        ls -lart
        if [ "$(params.revision)" != "" ]; then
          git checkout $(params.revision)
        fi