apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-backend
spec:
  workspaces:
    - name: source
  steps:
    - name: test
      image: python:3.12-slim
      workingDir: $(workspaces.source.path)/counter-app-backend
      env:
        - name: HOME
          value: /tekton/home
        - name: PIP_CACHE_DIR
          value: /tekton/home/.cache
      script: |
        export PATH=$HOME/.local/bin:$PATH
        echo "current working dir" 
        pwd
        echo "file list"
        ls -lart
        pip install --user --no-cache-dir -r requirements.txt
        pip install --user pytest httpx pytest-asyncio
        pytest test_main.py
        echo "Backend tests completed"